language: rust
env:
  global:
    - PROJECT_NAME=lindyndns
    - RUST_BACKTRACE=full
    - secure: dv+RBCrSypg/nlaahsb1aZDWM9cyjH4I4GrhJbLuJYWZ02R/yUBCzinz0Xq7Vczz1LAj7UobEbKi+P/IK6W2/mfDblYOvoHyDh2XrPZJ7qL47sTok/IuFLWfPNiYswKbbuEeFcq7SJWUdMtyEXoi88lNolLOQUZqzdzMYgpalCSG02tjzi9oG9XG5F7i3K75Hw/dFI53SeGvXqkcS+Qy43s1iV8QoU7rpnrNqSRMZUaClfPa9nPgurJ/u4l7E68fArPiKFaf7CGuEtfMYG8j8VW5Hjivy3+mLtocD+4ZamOjy+thZcmq5RX4bydLgmHmu8XuMJIsfeer1v6CtqXid61aSwiEnSc4PAuoalsjj+6iCJUEETvRS7Iqs0SUbag4ik4wgYwP3FZtpRK5Iw+t+cpI9SWagO/CYAAzBunet/OTrTH09cuvLuSf1j4tS0m2/I62wPXh+/JcMUY3UQOjDqKRsmbzo2PQSg+E6MeZfQXe7TncCW4I0J6MMFmfw2ZkIyK6xIvT3+i5dCi5ANZTuQQ/vqpcFRqvJjV3v9ahsH1TJ+iqg0qUfz4qengsR+hhQWrRnzpbvJE0/nbiuyaL5+DKrqunCTjL5ii+7fbPui6hnWFKStKYQPvvkrWVJE57TvGZ73Rf0oeFDWzghLXCp+AKbJ6cLipsANTwlR0ZMZI=
    - secure: jZc4fOWYRr8w7hYZyqd4Q7TChcEe2Mh/xg7wH698ifwQm80IHLY6CtQBHi2fTyndAeNej+x7vFUz4bxzVj66BVI9576pvuOCWqAGWVHnnPezEPEcnB4cyByaQigIG16GQ/0XKcVK5pZebbUcDW1eE59h+hc9puKow9DPg4Jsedvv7r6F9ObNyOgR0r9vMRC/nHlUCm1LjO2PgsTg8Ae4bskiH92XGME6OI0Xh1c2e4gJaJyaR6vR8wAW6pCaRtLRYzO98EISn2LyD10rjfA4H5HbosQZ4YcyuYnZLAVVBW7Fx+nJ8DNVbxYYuBtbM9tSE8/BNJVAKSP/mcwCGczkydcmAfibcFGauypb4m+wUD4a1V84T5Y9xewgOGcUeN+wJkAt7t5PxkL3hcFc1oYXl+hv0GvUl60kmA7Nr1qzuCrWhZUR8sRzTlnVVkkF7bTmN2t1SuUol/Ygq2IQUp0QuIupA9nrHic753ieUXhjjdOicKVkt+AsM00kv18P3kEqrtgcXzu/1QKTKQgGkZe5oMSdERPAmlxHVkQjtavvUaUd3HHvLo+MPOIyMfWxgeKBeyB86U2hMU55bQwTPfUCblyoOV3bNVkX/isOZqWYu+gO8r5zErzhgFWSBaOeKoEoLHwFckGAmRrBM8y28yZU0ap79TAh9O4wpaPAbKLOPlo=
    - secure: i8x/oSO7h4wSUuq0ZRsxzMe7PWtu4+BeCf10OS0TglGOxQJ78pYj6J4L1nR37aqoi9xDBB5dqarXsddXtQQX76fbSJ3K0BcNVEWlNm6K0nCPctOtH4hCVXZ603paqgV/vbv8R+RnvJVqogJM6WO3Xh/OAgUUi/aFIkZ1oV3gbhQhluFvAO0pO2WOSiT9q6RH7/AlXGGVqB3eVlF185FTsUBl3i5UqkPqWW1ZameJmKfgJhVQOQ7ONfrApyX8qV5SiR5shBi09bodcHLikP1JWHjOm1nFaDKSEf8nJ7UpueOCGodqltKiYzGG+OE/DDoFmQ7gmQ0g7IkwPfsOR5uXe0PlPCYfxLh3XpOD0tCfsY8gH5ilA0BB6Z4Pmc7DQCHSwNvXOEaFgA+S3TIXHKVjskuv3RGEJZ//BiRNWX8gJrFVqfiKhBJFGl9QvtCCVeYDUz69CNbkS0Fv7mpFKM6Cp39l8xCDt0IRZRQGV7+31ZL8zVv1a7/KqoN5IE1jxCSSTUkYjMedlZGosuobgFpkPlSgNu6dvaIPsD0/3BM7VVpQvwVhlJt0xKuVaYJUOfBNQKax/ZABmRcGCTv5gGuKrmGwomZ6MNN5gA9cbq8jkOUlOzAMAevV6/35KENKObEYGHDe23tT+1LOvFSeyqQscK29dgu+ItgD1qYufrcsR0k=
matrix:
  include:
    - os: linux
      dist: xenial
      rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu
    - os: osx
      rust: nightly
      env: TARGET=x86_64-apple-darwin
      sudo: required
    - os: windows
      rust: nightly
      filter_secrets: false
      env:
        - TARGET_ARCH=x86_64
        - TARGET=x86_64-pc-windows-msvc
        - PATH="/c/Program Files (x86)/NSIS/Bin:$PATH"
      sudo: required
    - os: windows
      rust: nightly
      filter_secrets: false
      env:
        - TARGET_ARCH=i686
        - TARGET=i686-pc-windows-msvc
        - PATH="/c/Program Files (x86)/NSIS/Bin:$PATH"
      sudo: required
script:
  - ci/build.sh
  - ci/test.sh
before_deploy:
  - ci/package.sh
cache:
  directories:
    - "${HOME}/.cargo"
before_cache:
  - rm -rf "${HOME}/.cargo/registry"
deploy:
  provider: releases
  file_glob: true
  file: deployment/*
  skip_cleanup: true
  overwrite: true
  draft: true
  on:
    branch: master
    tags: true
  api_key:
    secure: CpPhIAZD4yquhISO8VENFpyIUvvWM6UyO5tulPyezsDXr9aeD9QXTLOcDwLU2GnwoHOMeNjB6EsBT82oh/Zdr2246aNwVmCFSdmXzSUyK/k2485f4T0H3AyTJtPFcybynTBgnUSTzMoz7cRWCi2q6T7qKQTpVfv7R5NwQYrilNyrlQCEtL8BooSuMqUqdxVbdv5h006jxKRuayn+IvmvmjohLCmt279Tsa5Fl29TDWA3kwQCMbtswNPaNeA9V6LlHkAfmMq3/HLwTcZA+aCmGPd0qmGKB/ghwqUhKm0vU+2NjGyUFq8KDc/vxl9XDJtVYotB3PjPASKyUk4cAw4dwAbIAqMovfnB0RFDDQPBCgjyceO0+SpNjwn50P67Q9RXyRIi+W0I+qekontkIO/a1o5ZAV886W35sNBMtjUwjhDVmqYI9cvH3Tn0kb0Ia2we8fIhYRVzzHe09H2Nh+6BMIk9aziGegSuD8R3XqKCnazy1jhszcNBvRKmE7m7OkXl1hMnZMg7rtjTjGlL+NJ/pkumUkdCoKqaI02zuYqPECaSDeCrNLbU8XIdkW4huhcXE8ufxNgvxmFmzh0HQA09xSLOLNDTRRaiWW3rncv4zxI1KSUDudcOnF9rcSlcggJzKfu3uhAEVwhnwoKEb9izceFb7DKk8fzANexnkAm4aek=
