language: rust
env:
  global:
  - PROJECT_NAME=lindyndns
  - RUST_BACKTRACE=full
  - secure: dxDKfaOmGZM9kH7wv/W/zrLZfhMy1O8gDpti0ybbO323TI9kDW45egNzTQTwbUiYD87TawT99IC3gw9R6kok29YyHLQzhu1PNrMMEy8o+8dxoSzJnTfZY2oPy+7uqOGOKiApVJen8OI+a29/WYL9liJj5A4yXjoKMs+wa+KLxSjDaCPv3ZrEPresrk1JiTLPWWyNNCF7hR+ax/hG3EXvO+VHkkOBjodJZCgihSYmr0Y2s70cWODFCbKK5y+dnzEXMhZjR+bGUSJUmXDxkBhE1lxn7ia0d0tgEf4LM5PG2HWouA7dFgKTh35nAvQBoR2fyWDT7+pLfj/k2tmtyeJtDucbVHWVW1e/EovHfg1QsKM3rY/grWOvjkv3duZpM4Ej6Zlwd+l9iS5LaHan7h3sV+8bQLfKSZBvHcZPn89Rqih6xIsqbj4FkiC2R3CHle2dLqjd2A0VC6v7wLQ04ko4DsOlsUACMOOm2hYfMvXCqQ0FUwyUTFxYA7+gY4ebjnIh5IKYu14pPYQ4QqM/LcbM2fuRfIFWIwI5WXSWfIXJEN7smr0q/has2/YqgS+wiH7zf8VF3SKbHCKkcV1EqTsD7e0nu1KgKqdXTjYjPg4FOoRmHp/pTH+xPrCnTIjW9EHuIYmxil/PiaYcRJrLW+hOiTuxB1iNxmx+7VDcSG+xmj8=
  - secure: UAcmn3LRK4KztAld8zChi/EobhLtiyMmvYKFQGCZ6kRTbodZNc1YG8qhho7RuF7aQaxtGX80qWzPEx8DvPE5PjFjJFUSprNe5JwXW97tMTs/3AfgkLDPMpj2EuXO6WjzsrBfv51IiXF4AYQVOULlFEoFc+NOaJAdiSge9oiaQGjo+H6pRr63KJdp25E7iN1ml5WBOBa8QckXXaAFzCrZSzBlR7g7mlk7ZoOkuSmD+/AGPQaNaX8p25ffGOOtaweADIUUBtliGYmX29IP+SM7m3ze3xRLP4doXUa3N3vmSPW9NkimB4PzPNtPuTqCWAB/rxedZGFvnVg/6dz47T95o4LO8xT010QON56ISL+sioPwQY6fhUgf/Q21v/omcyxhBkWxvSkARlFoGmyHJLVngjhIFknfk3tTWZFYywTdOmb4cfpCpLFRSFyRxQlANZQhpmXPo6djM6+mKZjMItj3uV97w/PA6fhKt6YbEL72ZNvkiPcnug2lUyHiHnIqpLJEpWJ/NsbZ4gEH03h7ykU7OLVm+DPA1c7QGaiIZUWvwVFis2mKHXvw08oy05T57/y2+fYNLp4MgRpi8aTOj42Rib8j0ef9Xo7oRPj883vHxau556uu0VWQGcM3gGpADrzswKQrUCs9RPiPgJIa6m4RYy2DesLiLuQsdAoje/hgrlQ=
  - secure: VTycFtwBoj8oQJoqCt/jjdT0GNoUROk2imK/V4k0is+6kFWNesc9q8JAoB9kxaGWU40mLz4TMot+zSbuUMUHXks+UtVOIpKkiocRVWXRWF0ROLHMeJVJj2UI2D7HzUio9mL+Omkx2aQsUff1yguhvbvarXQr7i3r6OqzCgQ+5fZXj3AHUrVGak+MurKgRnA7yKPlFaAi0WqMrB8Hsmr44T3f4NyZrRzzrhXaCi2VRodFQq0A7cXIbqmqd8wCrzgfERgPZQacYGSTNhXFhYbMCdgNHoZDLcFOvYCgrswOjSNIj+G+25SOXszedqtj2HSKjgvffXoTgCSojSGfpM4zk5vlxd9i4Y/+yhiB07zYeeWu+ejBGHj1wXDKuWXWO1WXR+kcCqzX3Z0bvA1f5gZByXHq7eOqYcR1oU3er8hli4HS8DA7Xmi//NdRxWf+Fzy5kT5wvuT1VjMjouPQiDP/uJ49RCEhLJplzj05PcwBhPg6pZT2WuTPi6CstBS9Yf/++WVru0mQ/JJJmJcOUf8UM1KzAnIFOuwGDjFnhBM+v2ZG+fBLMs2sGIZjDB9i8FFsWMfKzxzJ9hg+OYX11VC2rBI1z6M2RUSZcN+jAxJNv7gdw9KspdX3tw3QQzJieeGbirnO7ILaEauAuxHX986LKXGbKBmF+bUmuBPwl10DDnM=
matrix:
  include:
  - os: linux
    dist: xenial
    rust: nightly
    env: TARGET=x86_64-unknown-linux-gnu
  - os: osx
    rust: nightly
    env: TARGET=x86_64-apple-darwin
    sudo: required
  - os: windows
    rust: nightly
    env: TARGET=x86_64-pc-windows-msvc
    sudo: required
script:
  - ".travis/build.sh"
  - ".travis/test.sh"
before_deploy:
  - ".travis/package.sh"
  - export RELEASE="$(ls deployment/*)"
  - export TRAVIS_TAG="preview"
cache:
  directories:
    - "${HOME}/.cargo"
before_cache:
  - rm -rf "${HOME}/.cargo/registry"
deploy:
  provider: releases
  file: "${RELEASE}"
  skip_cleanup: true
  overwrite: true
  draft: true
  on:
    branch: master
  api_key:
    secure: uaRr+l0vYNqTetNQ/1b5qROlXLYn9yeK1KZa6SEUqC3uId/4TVxhHfGrg/7QanX0YeMxBogaWj1r2+HzO5LAsAdViMTMcGSnsXVtpz7GQzPnOc5mX9LTvF9I6OThWXhtQrtc9WNSM1jOb3kRUyBzTya4R1xuajkdFamBC3fJjR+a+FmLqgdIvAIvjMGMzBwNaC0CLIisK8hOrjMacyL7mCZzYPIWAhzalrzqzhRoSj8usp2qkZhShfwa9cheMk0z2S+KdoQVY/IEidv93TiHlfPSuuvFX03QLRe1NBGwpP7OsAuvVQ6Lv+WEvknPU4lu9OWQvcKASUdm9Pft0RfZ+ANPEhSSKvBn0zUUXqa0+/54a1ClceXw694MtTEqeikgcbm5eAEqb08/IA1rmaW123xsDX8iTzhlnpzPuR3+zPZU8EBq6sw0FGmJ/3yvMmLjTK3uM6hph6quCayOXQrWXUMO1humlBCKryGqNQthfzljhZDAnZCoMiORCZXvfQIV2fjvMxgrZLMOb29DVj2o1xn8S+Rz3ddUs3xO8b+HsCBPyu0uCK0DUJHsDi6A2pgBEtYiFV4LRU1WgHav1rtEKk7b+DOZwMpB79P0hzBW5+fMVnqXPhMucCMAj8pOhg89jW5g2+ufoyhbJCrFYiZR6251iSkxN45uBMwt0qLXaTk=
