[package]
name = "lindyndns"
version = "0.0.0"
license = "MIT"
authors = ["John Ramsden <johnramsden@riseup.net>"]
edition = "2018"

[dependencies]
reqwest = "0.9.14"
clap = "~2.33.0"
serde_derive = "1.0.90"
toml = "0.5.0"
serde = "1.0.90"
http = "0.1.17"
serde_json = "1.0.39"
